apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minio-non-tls.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }} # You should define the desired size in your Values.yaml file