apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio-non-tls.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: {{ .Values.service.consoleTargetPort }}
      {{- if and (eq .Values.service.type "NodePort") (not (empty .Values.service.consoleNodePort)) }}
      nodePort: {{ .Values.service.consoleNodePort }}
      {{- end }}
    - name: s3
      port: {{ .Values.service.s3Port }}
      targetPort: {{ .Values.service.s3TargetPort }}
      {{- if and (eq .Values.service.type "NodePort") (not (empty .Values.service.s3NodePort)) }}
      nodePort: {{ .Values.service.s3NodePort }}
      {{- end }}
  selector:
    app: {{ include "minio-non-tls.name" . }}